[32m2025-07-04 12:11:57 +0200[0m - dagster - [34mDEBUG[0m - jaffle_shop_parallel_job - bdd99cde-24dc-41d5-a994-5e61d772eeea - 39299 - LOGS_CAPTURED - Started capturing logs in process (pid: 39299).
[32m2025-07-04 12:11:57 +0200[0m - dagster - [34mDEBUG[0m - jaffle_shop_parallel_job - bdd99cde-24dc-41d5-a994-5e61d772eeea - 39299 - jaffle_shop_products - STEP_START - Started execution of step "jaffle_shop_products".
/Users/dlthubgtm/Desktop/Aashish/Dagster Demo/Second Test/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py:610: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(
2025-07-04 12:11:59,500|[WARNING]|39299|8517099264|dlt|pipeline.py|run:707|The pipeline `run` method will now load the pending load packages. The data you passed to the run function will not be loaded. In order to do that you must run the pipeline again
[32m2025-07-04 12:12:11 +0200[0m - dagster - [34mERROR[0m - [31mjaffle_shop_parallel_job - bdd99cde-24dc-41d5-a994-5e61d772eeea - 39299 - jaffle_shop_products - STEP_FAILURE - Execution of step "jaffle_shop_products" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "jaffle_shop_products"::

AttributeError: 'NoneType' object has no attribute 'row_counts'

Stack Trace:
  File "/Users/dlthubgtm/Desktop/Aashish/Dagster Demo/Second Test/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/Users/dlthubgtm/Desktop/Aashish/Dagster Demo/Second Test/.venv/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/dlthubgtm/Desktop/Aashish/dlthub-education/workshops/demo_dagster/dlt-dagster-integration-parallel-pipeline/dlt_dagster_integration_parallel_pipeline/assets.py", line 33, in asset
    yield from dlt.run(context=context)
  File "/Users/dlthubgtm/Desktop/Aashish/Dagster Demo/Second Test/.venv/lib/python3.11/site-packages/dagster_dlt/dlt_event_iterator.py", line 77, in __next__
    return next(self._inner_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dlthubgtm/Desktop/Aashish/Dagster Demo/Second Test/.venv/lib/python3.11/site-packages/dagster_dlt/resource.py", line 294, in _run
    metadata = self.extract_resource_metadata(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dlthubgtm/Desktop/Aashish/Dagster Demo/Second Test/.venv/lib/python3.11/site-packages/dagster_dlt/resource.py", line 134, in extract_resource_metadata
    rows_loaded = dlt_pipeline.last_trace.last_normalize_info.row_counts.get(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0m
